TestApi/urls.py
from django.conf.urls import patterns, include, url
from rest_framework import routers,generics
from takeaway import views
from takeaway.views import *
from takeaway.models import *
from takeaway.forms import *
from django.views.generic.base import TemplateView


from django.contrib import admin
from django.contrib.auth.views import password_change
admin.autodiscover()

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'schools', views.SchoolViewSet)
router.register(r'courses', views.CourseViewSet)
#router.register(r'sessions', views.SessionViewSet)

router.register(r'tags', views.TagViewSet)
router.register(r'ratings', views.RatingViewSet)
router.register(r'notifications', views.NotificationViewSet)
router.register(r'courseInstances', views.CourseInstanceViewSet)
router.register(r'courseInstancesCreate', views.CourseInstanceCreateViewSet)
router.register(r'programs', views.ProgramViewSet)
router.register(r'sections', views.SectionViewSet)
router.register(r'status', views.StatusViewSet)
router.register(r'terms', views.TermViewSet)
router.register(r'takeawayprofiles', views.TakeAwayProfileViewSet)
router.register(r'favorites', views.FavoriteViewSet)
router.register(r'comments', views.CommentViewSet)
router.register(r'contactus', views.ContactUsViewSet)
router.register(r'emailSettings', views.EmailSettingsViewSet)
router.register(r'closedGroups', views.ClosedGroupViewSet)
router.register(r'sharedTakeaway', views.SharedTakeawayViewSet)
#router.register(r'takeaways_since_last_login', views.TakeAwayListSinceLastLoginList)




handler404 = 'takeaway.views.error'

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'takeaway.views.home', name='home'),
    url(r'^login/$', 'takeaway.views.home', name='login'),
    url(r'^profile/$', 'takeaway.views.profile', name='profile'),
    url(r'^handlelogin/$', 'takeaway.views.handlelogin', name='handlelogin'),
    url(r'^logout/$', 'takeaway.views.logoutuser', name='logoutuser'),
    url(r'^user/password/reset/$',
        'django.contrib.auth.views.password_reset',
        {'post_reset_redirect' : '/user/password/reset/done/'},
        name="password_reset"),
    (r'^user/password/reset/done/$',
        'django.contrib.auth.views.password_reset_done'),
    (r'^user/password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        'django.contrib.auth.views.password_reset_confirm',
        {'post_reset_redirect' : '/user/password/done/'}),
    (r'^user/password/done/$',
        'django.contrib.auth.views.password_reset_complete'),

    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
	url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
	url(r'^sessions/(?P<pk>-?[0-9]+)/$', SessionDetail.as_view(),name='session-detail'),
    url(r'^takeaways/(?P<pk>-?[0-9]+)/$', TakeAwayDetail.as_view(),name='takeaway-detail'),
	url(r'^takeaways/$', TakeAwayList.as_view(), name='takeaway-list'),
    url(r'^sessions/$', SessionList.as_view(), name='session-list'),

       url(r'^takeaways/index', 'takeaway.views.index', name='index'),
    url(r'^takeaway/initload', 'takeaway.views.initload', name='initload'),
    url(r'accounts/register/$', TakeAwayRegistrationView.as_view(),name = 'registration_register'),

    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^passwordchange/', include('django.contrib.auth.urls')),
    url(r'^load_courses/',  'takeaway.custom_school_data_load.load_isb_data', name='load_courses'),
    url(r'^load_wharton_courses/',  'takeaway.custom_school_data_load.load_wharton_data', ),

    # url(r'^contact/thankyou/', 'takeaway.views.thankyou'),
    # url(r'^contact/', 'takeaway.views.contactview'),
    url(r'^contact/', 'takeaway.views.ContactUs', name='contact_us'),
    url(r'^contact_login/','takeaway.views.ContactUsLogin',name='contact_us_login'),
    url(r'^landing/',TemplateView.as_view(template_name="newlanding.html")),
    url(r'^1/',TemplateView.as_view(template_name="landing.html")),
    url(r'^2/',TemplateView.as_view(template_name="landing2.html")),
    url(r'^3/',TemplateView.as_view(template_name="landing3.html")),
    url(r'^4/',TemplateView.as_view(template_name="landing4.html")),
    url(r'^5/',TemplateView.as_view(template_name="landing5.html")),
    url(r'^6/',TemplateView.as_view(template_name="landing6.html")),
    url(r'^grocery/',TemplateView.as_view(template_name="grocery.html")),
    url(r'^biryani/',TemplateView.as_view(template_name="homefood.html")),
    url(r'^demo/',TemplateView.as_view(template_name="demo.html")),
    url(r'^rating/',TemplateView.as_view(template_name="rating.html")),
    url(r'^can_user_post/','takeaway.views.can_user_post',),
    url(r'^play/','takeaway.views.play',name="play"),
    url(r'^load_demo/','takeaway.demo.create_play_ground', name='load_demo'),
    url(r'^test/','takeaway.views.test',),
    url(r'^get_leader_board/','takeaway.views.get_leader_board',),
    url(r'^chat/','takeaway.views.Chat',name='chat'),
    url(r'^takeaways_since_last_login/',TakeAwayListSinceLastLogin.as_view(),name='takeaways_since_last_login'),

)

takeaway/models.py
from django.db import models
from django.utils.encoding import smart_unicode
from django.contrib.auth.models import User
from django import forms
from django.core.mail import send_mail,mail_admins
from notifications import notify

import os
# Create your models here.

import logging
logger = logging.getLogger(__name__)

class School(models.Model):
    school_name = models.CharField(max_length=400)
    image_url = models.URLField(default='')

    def __unicode__(self):
        return smart_unicode(self.school_name)

class EmailFormat(models.Model):
    format = models.TextField()
    school = models.ForeignKey(School)

    def __unicode__(self):
        return smart_unicode(self.format)



class Course(models.Model):
     school = models.ForeignKey(School)
     course_name = models.CharField(max_length=400)
     course_desc = models.TextField()
     created_by = models.CharField(max_length=400)
     created_dt = models.DateTimeField(auto_now_add=True,auto_now=False)
     updated_dt = models.DateTimeField(auto_now_add=False,auto_now=True)

     # Maybe try file field and Image field here to associate a pdf/rtf/txt file for each course and maybe an image for each course
     # models.FileField(upload_to='documents/%Y/%m/%d')

     def  __unicode__(self):
        return smart_unicode(self.course_name)

     def get_enrolled_students(self):
        return self.students




#class EnrollmentManager(models.Manager):
#
#    def get_enrolled_students(course_obj):
#        return self.filter(course=course_obj)
#
#    def get_enrolled_courses(user):
#        return self.filter(student=user)

class Enrollment(models.Model):
    student = models.ForeignKey(User)
    course = models.ForeignKey(Course)
    #objects = EnrollmentManager()

    #def __unicode__(self):
    #    return smart_unicode(self.student + self.course)


class Tag(models.Model):
    name = models.CharField(max_length=100,unique=True)
    def __unicode__(self):
        return smart_unicode(self.name)



class Program(models.Model):
    school = models.ForeignKey(School)
    name= models.CharField(max_length=100)
    def __unicode__(self):
        return smart_unicode(self.name)


class Term(models.Model):
    school = models.ForeignKey(School)
    description= models.CharField(max_length=100)
    def __unicode__(self):
        return smart_unicode(self.description)


class Section(models.Model):
    school = models.ForeignKey(School)
    name= models.CharField(max_length=100)
    def  __unicode__(self):
        return smart_unicode(self.name)




class Status(models.Model):
    school = models.ForeignKey(School)
    value= models.CharField(max_length=100)
    def __unicode__(self):
        return smart_unicode(self.value)


class CourseInstance(models.Model):
    course = models.ForeignKey(Course)
    section =  models.ForeignKey(Section)
    # students = models.ManyToManyField(TakeAwayProfile)
    program = models.ForeignKey(Program)
    batch = models.IntegerField(max_length=100)
    year = models.IntegerField(max_length=100)
    status = models.ForeignKey(Status)
    term = models.ForeignKey(Term)
    def  __unicode__(self):
        return smart_unicode(self.course.course_name)


class Session(models.Model):
    courseInstance = models.ForeignKey(CourseInstance)
    session_name = models.CharField(max_length=1000)
    session_dt = models.DateField()
    created_dt = models.DateTimeField(auto_now_add=True,auto_now=False)
    updated_dt = models.DateTimeField(auto_now_add=False,auto_now=True)

    def __unicode__(self):
        return smart_unicode(self.session_name)

    # def save(self,*args,**kwargs):

    #     super(models.Model,self).save(*args,**kwargs)
    #     #kwargs.set('request') = self.request
    #     kwargs[ 'request' ] = self.request



class TakeAway(models.Model):
    courseInstance = models.ForeignKey(CourseInstance)
    session = models.ForeignKey(Session)
    notes = models.TextField()
    created_dt = models.DateTimeField(auto_now_add=True,auto_now=False)
    updated_dt = models.DateTimeField(auto_now_add=False,auto_now=True)
    user = models.ForeignKey(User)
    is_public = models.BooleanField(default=False)
    vote_count = models.IntegerField(default=0)
    average_rating = models.FloatField(default=0)
    total_raters = models.IntegerField(default=0)

    tags = models.ManyToManyField(Tag)

    def __unicode__(self):
        return smart_unicode(self.notes[:400])
    def toggle_public(self):
        if self.is_public:
            self.is_public = False
        else:
            self.is_public = True

class Comment(models.Model):
    takeaway = models.ForeignKey(TakeAway)
    notes = models.TextField()
    created_dt = models.DateTimeField(auto_now_add=True,auto_now=False)
    updated_dt = models.DateTimeField(auto_now_add=False,auto_now=True)
    user = models.ForeignKey(User)
    vote_count = models.IntegerField(default=0)
    average_rating = models.FloatField(default=0)
    total_raters = models.IntegerField(default=0)
    tags = models.ManyToManyField(Tag)

class Rating(models.Model):

    takeaway = models.ForeignKey(TakeAway)
    user = models.ForeignKey(User)
    rating_value = models.FloatField(default=0)
    already_rated = models.BooleanField(default=False) # If already rated then nothing can be changed.

    def __unicode__(self):
        return smart_unicode(self.rating_value)

    def set_rating(self,value):
        if self.already_rated :
            pass# do nothing as user is trying to double vote

        else :
            rating_value = value

class TakeAwayProfile(models.Model):
    CLASS_2014 = '2014'
    CLASS_2015 = '2015'
    CLASS_2016 = '2016'
    CLASS_2017 = '2017'
    YEAR_IN_SCHOOL_CHOICES = (
       (CLASS_2014, 'Class of 2014'),
       (CLASS_2015, 'Class of 2015'),
       (CLASS_2016, 'Class of 2016'),
       (CLASS_2017, 'Class of 2017'),
    )

    user = models.ForeignKey(User, unique=True)
   #avatar = models.ImageField("Profile Pic", upload_to="images/", blank=True, null=True)
   # first_name = models.CharField(max_length=200,blank = True)
   # last_name = models.CharField(max_length=200,blank = True)
   # username = models.CharField(max_length=200,unique= True)
    email = models.EmailField(unique= True)
    school =  models.ForeignKey(School)
    batch = models.CharField(max_length=200,choices=YEAR_IN_SCHOOL_CHOICES,
                                      default=CLASS_2016)
    program = models.ForeignKey(Program)
    courseInstances = models.ManyToManyField(CourseInstance,related_name='students')
   #password = models.CharField(max_length=500)



   # Not necessary right away
    takeaway_count = models.IntegerField(default=0)

    def __unicode__(self):
        return unicode(self.user.username)

class Vote(models.Model):

    VOTE_VALUES = (
    (1, 'UpVote'),
    (0, 'Nuetral'),
    (-1, 'DownVote'),
    )
    takeaway = models.ForeignKey(TakeAway)
    user = models.ForeignKey(User)
    vote_value = models.IntegerField(choices=VOTE_VALUES, default=0)
    already_voted = models.BooleanField(default=True) # If already voted then can only change the vote . Cannot stack on votes. Possible values 1 or -1 as of now

    def __unicode__(self):
        return smart_unicode(self.vote_value)

    def set_vote(self,value):
        if self.already_voted and vote_value == value :
            pass# do nothing as user is trying to double vote

        elif self.already_voted and vote_value <> value and (value == 1 or value == 0 or value == -1) :
            vote_value = value
        elif not self.already_voted and  (value == 1 or value == 0 or value == -1) :
            vote_value = value

class Favorite(models.Model):

    takeaway = models.ForeignKey(TakeAway)
    user = models.ForeignKey(User)
    courseInstance = models.ForeignKey(CourseInstance)

    def __unicode__(self):
        return smart_unicode(self.user)

# class NotificationSettings(models.Model):

#     EmailSettings = (
#     (0, 'NoEMail'),
#     (1, 'Instant'),
#     (2, 'Daily'),
#     )
#     user = models.ForeignKey(User)
#     mail_settings = models.IntegerField(choices=EmailSettings, default=2)
#     mail_when_newuser = models.BooleanField(default=True)
#     mail_when_takeaway = models.BooleanField(default=True)
#     mail_when_rated = models.BooleanField(default=True)
#     mail_when_rated = models.BooleanField(default=True)

#     def __unicode__(self):
#         return smart_unicode(self.user)

class EmailSettings(models.Model):

    EmailSettings = (
    (0, 'NoEMail'),
    (1, 'Instant'),
    (2, 'Daily'),
    )
    user = models.ForeignKey(User,blank=False)

    mail_when_newuser = models.IntegerField(choices=EmailSettings, default=2)
    mail_when_takeaway = models.IntegerField(choices=EmailSettings, default=2)
    mail_when_rated = models.IntegerField(choices=EmailSettings, default=0)
    mail_when_commented = models.IntegerField(choices=EmailSettings, default=0)
    created_dt = models.DateTimeField(auto_now_add=True,auto_now=False)
    updated_dt = models.DateTimeField(auto_now_add=False,auto_now=True)

    def __unicode__(self):
        return smart_unicode(self.user)

class PointEvent(models.Model):
    event = models.CharField(max_length=100,blank= False)
    points = models.IntegerField(default = 5)

    def __unicode__(self):
        return smart_unicode(self.event)

class UserEventLog(models.Model):
    user = models.ForeignKey(User,blank=True)
    event = models.ForeignKey(PointEvent,blank=True)
    points = models.IntegerField(default = 5)
    course_instance = models.ForeignKey(CourseInstance,blank=False)
    session = models.ForeignKey(Session,blank=False)
    course_instance = models.ForeignKey(CourseInstance,blank=False)
    created_dt = models.DateTimeField(auto_now_add=True,auto_now=False)
    updated_dt = models.DateTimeField(auto_now_add=False,auto_now=True)

    def __unicode__(self):
        return smart_unicode(self.event)


class ClosedGroup(models.Model):

takeaway/forms.py
from django.forms import ModelForm
from takeaway.models import TakeAway
from takeaway.models import TakeAwayProfile,ContactUs
from django import forms
from django.core.exceptions import ValidationError
from registration.forms import RegistrationForm,RegistrationFormUniqueEmail

# Create the form class
class TakeawayForm(ModelForm):
    class Meta:
        model=TakeAway
        fields=['notes']


class ChoiceFieldNoValidation(forms.ChoiceField):
    def validate(self, value):
        pass

class ProgramChoiceField(forms.ChoiceField):
    def validate(self, value):
        pass


class TakeawayProfileRegistrationForm(RegistrationFormUniqueEmail):


    CLASS_2014 = '2014'
    CLASS_2015 = '2015'
    CLASS_2016 = '2016'
    CLASS_2017 = '2017'
    YEAR_IN_SCHOOL_CHOICES = (
       (CLASS_2014, 'Class of 2014'),
       (CLASS_2015, 'Class of 2015'),
       (CLASS_2016, 'Class of 2016'),
       (CLASS_2017, 'Class of 2017'),
    )
    # FULL_TIME = 'FULL_TIME'
    # EVENING = 'EVENING'
    # PART_TIME = 'PART_TIME'
    # PROGRAM_CHOICES = (
    #    (FULL_TIME, 'Full Time MBA'),
    #    (EVENING, 'Evening MBA'),
    #    (PART_TIME, 'Part Time MBA'),
    # )
    # MONDAY = 'MONDAY'
    # WEDNESDAY = 'WEDNESDAY'
    # WEEKEND = 'Weekend'
    # SECTION_CHOICES = (
    #    (MONDAY, 'Monday'),
    #    (WEDNESDAY, 'Wednesday'),
    #    (WEEKEND, 'Weekend'),
    # )


    # batch = forms.CharField(max_length=200,choices=YEAR_IN_SCHOOL_CHOICES,
    #                                   default=CLASS_2016)
    # program = models.CharField(max_length=500,choices=PROGRAM_CHOICES,
    #                                  default=EVENING)
    # section = models.CharField(max_length=500,choices=SECTION_CHOICES,
    #                                  default=WEEKEND)

    school = forms.CharField()
    # email = forms.CharField()
    firstname = forms.CharField()
    lastname = forms.CharField()
    batch = forms.ChoiceField(choices=YEAR_IN_SCHOOL_CHOICES,)
    program = ProgramChoiceField()

    # class Meta:
    #     model=TakeAwayProfile
    #     fields=['email','school','batch','program','section']


class ContactForm(forms.ModelForm):

    subject = forms.CharField(max_length=100,help_text="Subject")
    message = forms.CharField(help_text="Message")
    sender = forms.EmailField(help_text="Your email")
    cc_myself = forms.BooleanField(help_text="cc_myself",required=False)

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = ContactUs

takeaway/templates/chat.html
    <html>
  <head>
    <meta charset='utf-8' />
    <script src='https://cdn.firebase.com/js/client/1.0.21/firebase.js'></script>
    <script src='https://cdn.firebase.com/js/simple-login/1.6.3/firebase-simple-login.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.2/jquery.min.js'></script>

    <!-- Download from https://github.com/firebase/firechat -->
    <link rel='stylesheet' href='/static/takeaway/css/firechat.min.css' />
    <link rel='stylesheet' href='/static/takeaway/css/app.css' />
    <script src='/static/takeaway/js/lib/firechat.min.js'></script>
  </head>
  <body>
  <script type='text/javascript'>
      // Create a new Firebase reference, and a new instance of the Login client
      var chatRef = new Firebase('https://blinding-inferno-5308.firebaseio.com/chat');
      var auth = new FirebaseSimpleLogin(chatRef, function(err, user) {
        // Once authenticated, instantiate Firechat with our user id and user name
        if (user) {
          var chat = new FirechatUI(chatRef, document.getElementById('firechat-wrapper'));
          chat.setUser('{{user.id}}', '{{user.username}}');
        }
      });

    </script>
    <div id='firechat-wrapper'>
      <a href='#' onclick='auth.login("anonymous")'>Login</a>
    </div>
  </body>
</html>

takeaway/templates/contact_us.html
{% extends "registration/base.html" %}
{% load i18n %}
{% block content %}
        

        <form id="category_form" method="post" action="/contact/" >
                            <h1>Contact Us</h1>

        
            {% csrf_token %}
            {{ form.subject.errors }}


            <div class="form-group" >
<p><label class="control-label col-lg-3" for="id_subject" >{% trans 'Subject:' %}</label>{{ form.subject }}</p>
</div>
            {{ form.message.errors }}

<div class="form-group">
<p><label class="control-label col-lg-3" for="id_message" >{% trans 'Message:' %}</label>
<textarea name="message" id="message" rows="4" cols="20" ></textarea></p>
</div>
            {{ form.email.errors }}

<div class="form-group" >
<p><label class="control-label col-lg-3" for="id_email" >{% trans 'E-mail:' %}</label>{{ form.sender }}</p>
</div>


           

            <input class="btn btn-primary col-lg-offset-3"type="submit" name="submit" value="Send" />
            <br>{{message}}</br>


        </form>
		


{% endblock %}
        
   

takeaway/templates/contact_us_login.html
{% extends "registration/base.html" %}
{% load i18n %}
{% block content %}
        

        <form id="category_form" method="post" action="/contact_login/" >
                            <h1>Contact Us</h1>

        
            {% csrf_token %}
            {{ form.subject.errors }}


            <div class="form-group" >
<p><label class="control-label col-lg-3" for="id_subject" >{% trans 'Subject:' %}</label>{{ form.subject }}</p>
</div>
            {{ form.message.errors }}

<div class="form-group">
<p><label class="control-label col-lg-3" for="id_message" >{% trans 'Message:' %}</label>
<textarea name="message" id="message" rows="4" cols="20" ></textarea></p>
</div>
            {{ form.email.errors }}

<div class="form-group" >
<p><label class="control-label col-lg-3" for="id_email" >{% trans 'E-mail:' %}</label>{{ form.sender }}</p>
</div>


           

            <input class="btn btn-primary col-lg-offset-3"type="submit" name="submit" value="Send" />
            <br>{{message}}</br>


        </form>
        


{% endblock %}
        
   

takeaway/templates/copyright.html
<div class="copyright">
   <span style="color:#000; margin-left: 600px;
">copyright © 2014 Takeaway Pro.</span>
</div>

takeaway/templates/error.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <!-- Title here -->
        <title>404 Error - MetroKing</title>
        <!-- Description, Keywords and Author -->
        <meta name="description" content="Your description">
        <meta name="keywords" content="Your,Keywords">
        <meta name="author" content="ResponsiveWebInc">

        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- Styles -->
        <!-- Bootstrap CSS -->
        <link href="/static/takeaway/css/bootstrap.min.css" rel="stylesheet">
        <!-- Font awesome CSS -->
        <link href="/static/takeaway/css/font-awesome.min.css" rel="stylesheet">
        <!-- Custom CSS -->
        <link href="/static/takeaway/css/style.css" rel="stylesheet">

        <!-- Favicon -->
        <link rel="shortcut icon" href="#">
    </head>

    <body>

<!-- Form area -->
<div class="error-page">
  <div class="container-fluid">

    <div class="row-fluid">
      <div class="span12">
        <!-- Widget starts -->
            <div class="widget wblue">
              <!-- Widget head -->
              <div class="widget-head">
                <i class="fa fa-question-sign"></i> Error
              </div>

              <div class="widget-content">
                <div class="padd error">

                    <h1>Oops!!! It's 404</h1>
                    <p>A fancy witty message will come here !!! Wait for it </p>
                    <br />


                    <br />
                    <div class="horizontal-links">
                    <a href="{% url 'index'%}">Home</a> | <a href="#">About Us</a> | <a href="#">Contact us</a> | <a href="#">FAQ</a>
                    </div>
                </div>
              </div>
                <div class="widget-foot">
                  <!-- Footer goes here -->
                </div>
            </div>
      </div>
    </div>
  </div>
</div>


        <!-- Javascript files -->
        <!-- jQuery -->
        <script src="/static/takeaway/js/lib/jquery.js"></script>
        <!-- Bootstrap JS -->
        <script src="/static/takeaway/js/lib/bootstrap.min.js"></script>
        <!-- Respond JS for IE8 -->
        <script src="/static/takeaway/js/lib/respond.min.js"></script>
        <!-- HTML5 Support for IE -->
        <script src="/static/takeaway/js/lib/html5shiv.js"></script>
    </body>
</html>

takeaway/templates/test.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>To-do App in Backbone.js</title>

  <!-- ========= -->
  <!--    CSS    -->
  <!-- ========= -->
  <style type="text/css">

  </style>
</head>
<body>
  <!-- ========= -->
  <!-- Your HTML -->
  <!-- ========= -->
  <div>
  <span> Public  </span>
  <span> Takeaway</span>
  </div>
  <section id="todoapp">

  </section>
  <div id="test">
    Hi, I will be removed
  </div>



  <!-- ========= -->
  <!-- Libraries -->
  <!-- ========= -->
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.3.3/underscore-min.js" type="text/javascript"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/backbone.js/0.9.2/backbone-min.js" type="text/javascript"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/backbone-localstorage.js/1.1.9/backbone.localStorage-min.js" type="text/javascript"></script>
  <script src="/static/takeaway/js/jquery.cookie.js" type="text/javascript"></script>


  <!-- =============== -->
  <!-- Javascript code -->
  <!-- =============== -->


<script type="text/template" id="takeaway-templates">
  <div><input type="checkbox" <% if(is_public) print('checked')%>><%= notes%></div>
</script>

  <script type="text/javascript">

$("#test").click(function(){
  $("#test").html("New content");
});



  var Takeaway = Backbone.Model.extend({

    urlRoot: '/takeaways',

    toggle: function(){
      if(this.get('is_public')){
        this.set({'is_public':false});
      }else{
        this.set({'is_public':true});
      }
      this.save();
    }

  });
    var TakeawayView = Backbone.View.extend({
        render: function(){
           var template = _.template($('#takeaway-templates').html(),this.model.toJSON());
            this.$el.html(template);
            return this;
        },
        events:{"click input[type=checkbox]":"toggleVisibility"},
        toggleVisibility: function(){
          this.model.toggle();
        }
    });

    var TakeawayList = Backbone.Collection.extend({
        model: Takeaway,
        url: '/takeaways/'
    });

    var TakeawayListView = Backbone.View.extend({

        render: function(){
            this.collection.forEach(this.addOne,this);
            return this;
        },
        addOne: function(takeaway){
              var takeawayObject = new Takeaway();
              takeawayObject.set(takeaway);
              var takeawayView = new TakeawayView({model:takeawayObject});
              this.$el.append(takeawayView.render().el);
        }
    });

var takeaway = new Takeaway();


var takeawayList = new TakeawayList();
   var takeaways = takeaway.fetch({success: function(collection, response){
     var takeawayListView = new TakeawayListView({collection:collection.attributes.results});
    $("#todoapp").append(takeawayListView.render().el);
   }});

var csrftoken = $.cookie("csrftoken");

function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});

</script>

</body>
</html>